spring:
  application:
    name: tiendaonline

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # Para configurar la actualización automatica cuando una clase Entidad se le
  # agregan nuevos campos
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  config:
    import:
      optional:file:.env[.properties]
